---
# tasks/build_tools.yml

- name: build_tools | install build related packages and libraries
  apt: pkg=$item state=latest update_cache=yes
  with_items:
    - python-dev
    - libcppunit-dev
    - libunwind7-dev
    - autotools-dev
    - libltdl-dev
    - libtool
    - autoconf
    - autopoint
    - libcurl3
    - libcurl4-openssl-dev
    - liblcms2-2
    - build-essential
